server:
  port: 8092
spring:
  application:
    name: mall-upload
  servlet:
    multipart:
      max-file-size: 5MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1010/eureka
