elm:
  db:
    host: 127.0.0.1
    username: root
    pw: 123456

  data:
    redis:
      host: 127.0.0.1
      password:
      database: 5

  nacos:
    server-addr: 172.26.11.128:8848
    username: nacos
    pw: 123456